on:
  issues:
    types: [opened, labeled]
name: Issues
jobs:
  issueHandler:
    name: IssueHandler
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: IssueHandler
      uses: Ash258/Scoop-GithubActions@stable-win
      if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
      env:
        SHOVEL: '1'
        GITH_EMAIL: cabera.jakub@gmail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
